[[ ! -x "$(command -v exa)" ]] || alias ls="exa --icons --group-directories-first"
[[ ! -x "$(command -v bat)" ]] || alias cat="bat --style=auto"
[[ ! -x "$(command -v batcat)" ]] || alias cat="batcat --style=auto"
[[ ! -x "$(command -v mktemp)" ]] || alias cdtemp="cd $(mktemp -d)"
[[ ! -x "$(command -v notepad++.exe)" ]] || alias npp="notepad++.exe"
