[".oh-my-bash"]
    type = "archive"
    url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/starship"]
    type = "archive-file"
    url = "https://github.com/starship/starship/releases/download/v1.19.0/starship-x86_64-unknown-linux-musl.tar.gz"
    path = "starship"

