[".oh-my-bash"]
    type = "archive"
    url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/starship"]
    type = "archive-file"
    url = "https://github.com/starship/starship/releases/download/v1.19.0/starship-x86_64-unknown-linux-musl.tar.gz"
    path = "starship"
[".local/bin/fzf"]
    type = "archive-file"
    url = "https://github.com/junegunn/fzf/releases/download/0.53.0/fzf-0.53.0-linux_amd64.tar.gz"
    path = "fzf"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz"
    path = "fd-v10.1.0-x86_64-unknown-linux-musl/fd"
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/v0.18.21/eza_x86_64-unknown-linux-musl.zip"
    path = "eza"
[".local/bin/zoxide"]
    type = "archive-file"
    url = "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.4/zoxide-0.9.4-x86_64-unknown-linux-musl.tar.gz"
    path = "zoxide"
[".local/bin/bat"]
    type = "archive-file"
    url = "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-unknown-linux-musl.tar.gz"
    path = "bat-v0.24.0-x86_64-unknown-linux-musl/bat"
