[".oh-my-bash"]
    type = "archive"
    url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/starship"]
    type = "archive-file"
    url = 'https://github.com/starship/starship/releases/download/v1.19.0/starship-{{ .chezmoi.arch | replace "amd64" "x86_64" | replace "arm64" "aarch64" | replace "386" "i686" }}-{{ .chezmoi.os | replace "linux" "unknown" | replace "darwin" "apple" | replace "freebsd" "unknown" }}-{{ .chezmoi.os }}{{ .chezmoi.os | replace "linux" "-musl" | replace "darwin" "" | replace "freebsd" "" }}.tar.gz'
    path = "starship"

