export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NPM_PREFIX_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/npm"
export NPM_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/npm"
export NPM_INIT_MODULE="${XDG_CONFIG_HOME:-$HOME/.config}/npm/config/npm-init.js"
export NPM_LOGS_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/npm/logs"
export NVM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvm"